version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    networks:
      - todo-network
    restart: always

  todo-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_api_container
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - todo-network
    restart: always

networks:
  todo-network:
    driver: bridge
